import { Diagram } from "./dsl";

export default function notificationSystem() {
  return new Diagram("Notification System", "One queue + worker pool per channel isolates slow or failing providers")
    .zone("Per-channel queues", 2, 0, 1, 4, "#e8590c")
    .zone("Channel workers", 3, 0, 1, 4, "#0c8599")
    .node("producers", "Internal services (billing, social, marketing)", 0, 1.5, "client", { h: 1.2 })
    .node("api", "Notification service (validate, dedupe, render)", 1, 1.5, "service", { h: 1.2 })
    .node("dedup", "Idempotency keys (Redis)", 1, -0.4, "cache")
    .node("prefs", "User prefs, device tokens, templates", 1, 3.4, "db")
    .node("q1", "iOS push", 2, 0, "queue")
    .node("q2", "Android push", 2, 1, "queue")
    .node("q3", "SMS", 2, 2, "queue")
    .node("q4", "Email", 2, 3, "queue")
    .node("w1", "APNs workers", 3, 0, "worker")
    .node("w2", "FCM workers", 3, 1, "worker")
    .node("w3", "SMS workers", 3, 2, "worker")
    .node("w4", "Email workers", 3, 3, "worker")
    .node("p1", "APNs", 4, 0, "external")
    .node("p2", "FCM", 4, 1, "external")
    .node("p3", "Twilio", 4, 2, "external")
    .node("p4", "SendGrid / SES", 4, 3, "external")
    .node("retry", "Retry queue + DLQ (backoff)", 3, 4.4, "queue")
    .node("log", "Notification log (status, opens)", 4, 4.4, "db")
    .edge("producers", "api", "send()")
    .edge("api", "dedup", "seen?")
    .edge("api", "prefs", "opt-in? tokens")
    .edge("api", "q1", undefined, { async: true })
    .edge("api", "q2", undefined, { async: true })
    .edge("api", "q3", undefined, { async: true })
    .edge("api", "q4", undefined, { async: true })
    .edge("q1", "w1", undefined, { async: true })
    .edge("q2", "w2", undefined, { async: true })
    .edge("q3", "w3", undefined, { async: true })
    .edge("q4", "w4", undefined, { async: true })
    .edge("w1", "p1")
    .edge("w2", "p2")
    .edge("w3", "p3")
    .edge("w4", "p4")
    .edge("w4", "retry", "5xx / timeout", { async: true })
    .edge("w4", "log", "status")
    .note("Every worker retries via the retry queue and writes status to the log.", 2, 5.3)
    .build();
}
